# netlify.toml
[build]
  command = "composer install --no-dev --optimize-autoloader && php build.php"
  publish = "public"
  environment = { PHP_VERSION = "8.1" }

# === Fix ?page=... routing ===
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/?page=landing"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/?page=login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/?page=signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/?page=dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/?page=tickets"
  to = "/tickets.html"
  status = 200

# === Fallback for any unknown path ===
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 404